// Package relay implements botjim's relay mode: two machines that cannot
// reach each other pair up through a broker and transfer end-to-end
// encrypted — the relay shuffles opaque bytes and nothing else.
//
//	botjim relay                      run the broker
//	botjim send --via R PATH...       offer (prints a pairing code)
//	botjim recv --via R --code C      take, receive into --dest
//
// Security model:
//   - the pairing code is 125 bits, generated by the sender and shared
//     out-of-band; the relay matches peers on SHA-256(code) only, which
//     is safe at this entropy (offline brute-force is infeasible — a PAKE
//     would add nothing until codes are human-memorable weak secrets)
//   - after pairing, both peers run an X25519 exchange authenticated by
//     the code (HKDF-psk) and confirm with mutually verified MACs; the
//     entire botjim session (FSY1 handshake onward) then travels inside
//     a ChaCha20-Poly1305 record layer, so the relay can neither read
//     nor tamper (tampering is detected) — it sees only sizes and timing
//   - codes are one-shot: a slot is consumed by the first taker
package relay

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// crockford is Crockford base32 without I, L, O, U — unambiguous to read
// aloud and type.
const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

const codeChars = 25 // 25 * 5 bits = 125 bits of entropy

// GenerateCode returns a fresh pairing code (raw, no separators).
func GenerateCode() string {
	raw := make([]byte, 16) // 128 bits, one spare
	if _, err := rand.Read(raw); err != nil {
		panic("relay: entropy source failed: " + err.Error())
	}
	var b strings.Builder
	bits := 0
	val := 0
	for _, by := range raw {
		val = val<<8 | int(by)
		bits += 8
		for bits >= 5 {
			b.WriteByte(crockford[(val>>(bits-5))&31])
			bits -= 5
		}
	}
	for b.Len() < codeChars {
		b.WriteByte(crockford[val&31])
		val >>= 5
	}
	return b.String()[:codeChars]
}

// NormalizeCode strips separators and upper-cases.
func NormalizeCode(code string) string {
	repl := strings.NewReplacer("-", "", " ", "", "\t", "")
	return strings.ToUpper(repl.Replace(code))
}

// ValidateCode enforces the entropy floor: relay matching relies on the
// code being un-guessable, so weak user-chosen codes are rejected.
func ValidateCode(code string) error {
	c := NormalizeCode(code)
	if len(c) < codeChars {
		return fmt.Errorf("relay code too short: need %d base32 characters (let botjim generate one)", codeChars)
	}
	for _, r := range c {
		if !strings.ContainsRune(crockford, r) {
			return fmt.Errorf("relay code has invalid character %q (base32: no I, L, O, U)", r)
		}
	}
	return nil
}

// FormatCode renders a code in dash-separated groups of five.
func FormatCode(code string) string {
	c := NormalizeCode(code)
	var parts []string
	for i := 0; i < len(c); i += 5 {
		end := i + 5
		if end > len(c) {
			end = len(c)
		}
		parts = append(parts, c[i:end])
	}
	return strings.Join(parts, "-")
}

// codeID is what the broker matches on — it never sees the code itself.
func codeID(code string) string {
	sum := sha256.Sum256([]byte("botjim-relay-id/v1/" + NormalizeCode(code)))
	return hex.EncodeToString(sum[:])
}
